Repository intlify/vue-i18n-locale-message, pull requests merged in 2020-01, with the labels that each got.

#50 status feature
  .eslintrc.js
  .github/workflows/release.yml
  README.md
  package.json
  src/commands/infuse.ts
  src/commands/squeeze.ts
  src/commands/status.ts
  src/index.ts
  src/infuser.ts
  src/utils.ts
  test/commands/__mocks__/l10n-service-provider.js
  test/commands/status.test.ts
  test/utils.test.ts
  types/index.d.ts
Labels: PR: unreviewed, Type: Feature

#51 minor release v0.11.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#52 --format option feature
  src/commands/pull.ts
  test/commands/pull.test.ts
  types/index.d.ts
Labels: PR: unreviewed, Type: Feature

#53 minor release v0.12.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#54 fix diff command build error
  CHANGELOG.md
  package.json
  src/commands/diff.ts
Labels: PR: unreviewed, Type: Bug

#55 minor release v0.12.0
  .github/workflows/release.yml
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#56 export command feature
  src/commands/export.ts
  test/commands/export.test.ts
  types/index.d.ts
Labels: PR: unreviewed, Type: Feature

#58 minor release v0.13.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#61 Add dryRun on infuse command
  src/commands/infuse.ts
  test/__snapshots__/cli.test.ts.snap
  test/commands/infuse.test.ts
Labels: PR: reviewed-approved, Type: Improvement

#59 support --format option for import command
  src/commands/export.ts
  src/commands/import.ts
  src/utils.ts
  test/commands/export.test.ts
  test/commands/import.test.ts
  test/fixtures/locales/ja
  types/index.d.ts
Labels: PR: unreviewed, Type: Improvement

#62 patch release v0.13.1
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#63 improve process.exit(1) when the translation is not finished yet
  src/commands/status.ts
  test/commands/status.test.ts
Labels: PR: unreviewed, Type: Improvement

#64 patch release v0.13.2
  .github/workflows/release.yml
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#66 process.exit(1) for detect difference with diff command
  src/commands/diff.ts
  src/commands/status.ts
  test/commands/diff.test.ts
Labels: PR: unreviewed, Type: Improvement

#67 patch release v0.13.3
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#68 fix diff exit code
  src/commands/diff.ts
  test/commands/diff.test.ts
Labels: PR: unreviewed, Type: Improvement

#69 patch release v0.13.4
  CHANGELOG.md
  package.json
Labels: PR: unreviewed

#71 fix reverse diff
  src/commands/diff.ts
  test/commands/__snapshots__/diff.test.ts.snap
Labels: PR: unreviewed, Type: Bug

#72 change status command exit code
  src/commands/status.ts
  test/commands/status.test.ts
Labels: PR: unreviewed, Type: Improvement

#73 patch release v0.13.5
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#74 list command feature
  README.md
  package.json
  src/commands/list.ts
  test/commands/__snapshots__/list.test.ts.snap
  test/commands/list.test.ts
  yarn.lock
Labels: PR: unreviewed, Type: Feature

#75 minor release v0.14.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#78 feat: bundle and namespace features
  package.json
  src/commands/diff.ts
  src/commands/fails/diff.ts
  src/commands/fails/exitcode.ts
  src/commands/fails/fail.ts
  src/commands/fails/list.ts
  src/commands/fails/status.ts
  src/commands/infuse.ts
  src/commands/list.ts
  src/commands/squeeze.ts
  src/commands/status.ts
  src/utils.ts
  test/__snapshots__/cli.test.ts.snap
  test/__snapshots__/utils.test.ts.snap
  test/commands/__snapshots__/infuse.test.ts.snap
  test/commands/__snapshots__/squeeze.test.ts.snap
  test/commands/__snapshots__/status.test.ts.snap
  test/commands/diff.test.ts
  test/commands/fails/diff.test.ts
  test/commands/fails/list.test.ts
  test/commands/fails/status.test.ts
  test/commands/infuse.test.ts
  test/commands/list.test.ts
  test/commands/squeeze.test.ts
  test/commands/status.test.ts
  test/fixtures/external.ts
  test/fixtures/namespace.json
  test/fixtures/packages/package1/locales/en/common.json
  test/fixtures/packages/package1/locales/ja/common.json
  test/fixtures/packages/package2/locales/en/profile.json
  test/fixtures/packages/package2/locales/ja/profile.json
  test/helper.ts
  test/utils.test.ts
  types/index.d.ts
  yarn.lock
Labels: PR: unreviewed, Type: Feature

#79 minor release v0.15.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#80 breaking: change squeeze bundle related option name
  src/commands/infuse.ts
  src/commands/squeeze.ts
  src/utils.ts
  test/__snapshots__/cli.test.ts.snap
  test/commands/infuse.test.ts
  test/fixtures/external.ts
  test/utils.test.ts
  types/index.d.ts
Labels: PR: unreviewed, Type: Breaking

#81 minor release v0.16.0
  CHANGELOG.md
  package.json
Labels: PR: unreviewed, release

#83 feat: define LocaleMessageDictionary type
  src/utils.ts
  types/index.d.ts
Labels: PR: unreviewed, Type: Feature
